New signature algorithms: ECC384 + ECC521
wolfSSL/wolfBoot pull request #188
Opened 2022-03-24 13:30 UTC by danielinux

- [x] Add support in wolfBoot
- [x] Add support in C key tools
- [ ] Add support in Python key tools
- [ ] Add 'factory' test
- [x] Add 'update' test
- [ ] Add 'corrupted' test
- [ ] Add 'bad version' test

2022-03-31 19:07 UTC, dgarske requested changes
Great work! Just a few minor cleanups. Also do you want to squash this PR?

2022-03-31 19:07 UTC, dgarske commented on tools/keytools/sign.c
> +                    *pubkey = *key_buffer; /* first 64 bytes is public portion */
Please update comment. First 96 bytes.

2022-03-31 19:07 UTC, dgarske commented on tools/keytools/sign.c
> +                ret = wc_ecc_import_unsigned(&key.ecc, *key_buffer, (*key_buffer) + 48,
Line length check

2022-03-31 19:07 UTC, dgarske commented on tools/keytools/sign.c
> +                ret = wc_ecc_import_unsigned(&key.ecc, *key_buffer, (*key_buffer) + 66,
Line length check

2022-03-31 19:07 UTC, dgarske commented on tools/keytools/sign.c
> +                    *pubkey = *key_buffer; /* first 64 bytes is public portion */
Please update comment. not 64 bytes.

2022-04-01 07:33 UTC, danielinux commented
Good point, I'll squash these commits after your final review. I left them separate for now, for a more comfortable check of the changes suggested for `sign.c` in 886ad0f

2022-04-01 18:43 UTC, dgarske approved these changes
Thanks

2022-04-01 19:29 UTC, merged