New signature algorithm: RSA 3072
wolfSSL/wolfBoot pull request #205
Opened 2022-05-30 14:05 UTC by danielinux

2022-05-30 14:07 UTC, julek-wolfssl requested changes

2022-05-30 17:57 UTC, danielinux commented
@dgarske please hold the review, I'm fixing all the tests

2022-05-31 15:20 UTC, danielinux commented
Ready for review

2022-05-31 16:55 UTC, dgarske approved these changes
Great work! Thanks

2022-05-31 16:55 UTC, merged