STM32 QSPI Flash support
wolfSSL/wolfBoot pull request #254
Opened 2022-12-06 19:00 UTC by dgarske

* STM32 QSPI Flash support.
* Refactor SPI to allow different GPIO base/AF for each pin.

Tested on STM32H753ZI hardware.

2022-12-06 22:02 UTC, tatowicz approved these changes
Small comment looks good otherwise

2022-12-06 22:14 UTC, dgarske commented on test-app/app_stm32h7.c
> +    reg = GPIOD_AFRH & ~(0xf << ((UART_TX_PIN & 0x07)*4));
No

2022-12-09 09:14 UTC, danielinux approved these changes

2022-12-19 12:09 UTC, danielinux commented
:x: 

SPI jenkins test fails on this branch
(`test-21-forward-update-no-downgrade-SPI` does not boot when SPI is on)

:x:

2022-12-20 08:02 UTC, danielinux requested changes
There is an issue in stm_gpio_config. 

By fixing this, spi test 21 boots, but fails to complete the update afterwards.

2022-12-20 08:50 UTC, danielinux commented on hal/spi/spi_drv_stm32.c
> -    reg = SPI_PIO_PUPD & ~(0x03 <<  (SPI1_CLOCK_PIN * 2));
Please add a `PLATFORM_stm32l0` exception in `stm_pins_setup` for stm32l0 to set the appropriate pulldown and ospd during SPI pin initialization

2022-12-20 12:58 UTC, danielinux commented
Closing in favor of #264

2022-12-20 12:58 UTC, closed without merging