Allow encrypted images in MMU targets
wolfSSL/wolfBoot pull request #282
Opened 2023-02-26 00:15 UTC by danielinux

This simple change should allow using encrypted images in VMM targets, addressing feature request #280

2023-02-27 16:59 UTC, dgarske approved these changes
Wow, just two lines to enable encrypted application partition use? Can you add some documentation on which build options to use? This will be used with the new LS1028A support @tatowicz is doing.

2023-03-09 16:13 UTC, dgarske requested changes
```
$ cp ./config/examples/raspi3-encrypted.config .config
$ make clean && make
...
aarch64-none-elf-gcc -D"WOLFBOOT_SIGN_RSA4096"  -D"FILL_BYTE=0xFF" -D"EXT_ENCRYPTED=1" -DWOLFSSL_AES_COUNTER -DWOLFSSL_AES_DIRECT -DENCRYPT_WITH_AES256 -DWOLFSSL_AES_256 -O0 -g -ggdb3 -D"DEBUG" -D"WOLFBOOT_NO_PARTITIONS" -D"WOLFBOOT_HASH_SHA3_384" -DIMAGE_HEADER_SIZE=1024  -g -ggdb -Wall -Wstack-usage=1024 -ffreestanding -Wno-unused -DPLATFORM_raspi3 -I../include -nostartfiles -DARCH_AARCH64 -march=armv8-a -DNO_QNX -DARCH_FLASH_OFFSET=0x0 -DMMU -DWOLFBOOT_DUALBOOT -D"EXT_ENCRYPTED=1" -I../lib/wolfssl -c -o ../src/libwolfboot.o ../src/libwolfboot.c
../src/libwolfboot.c: In function 'decrypt_header':
../src/libwolfboot.c:694:9: warning: implicit declaration of function 'crypto_set_iv' [-Wimplicit-function-declaration]
  694 |         crypto_set_iv(encrypt_iv_nonce, i / ENCRYPT_BLOCK_SIZE);
      |         ^~~~~~~~~~~~~
../src/libwolfboot.c:695:9: warning: implicit declaration of function 'crypto_decrypt' [-Wimplicit-function-declaration]
  695 |         crypto_decrypt(dec_hdr + i, src + i, ENCRYPT_BLOCK_SIZE);
      |         ^~~~~~~~~~~~~~
../src/libwolfboot.c: In function 'wolfBoot_get_blob_version':
../src/libwolfboot.c:713:13: warning: implicit declaration of function 'crypto_init' [-Wimplicit-function-declaration]
  713 |         if (crypto_init() < 0)
      |             ^~~~~~~~~~~
../src/libwolfboot.c: In function 'wolfBoot_erase_encrypt_key':
../src/libwolfboot.c:994:5: warning: implicit declaration of function 'ForceZero' [-Wimplicit-function-declaration]
  994 |     ForceZero(ENCRYPT_KEY, ENCRYPT_KEY_SIZE + ENCRYPT_NONCE_SIZE);
      |     ^~~~~~~~~
```

2023-03-09 17:38 UTC, danielinux commented
These warnings are from the test application, which is not used in this example. A linux kernel `Image` is used instead.

Target.md suggests `make wolfboot.bin`. I'm setting this as default main build artifact in the next commit.

2023-03-09 20:16 UTC, dgarske approved these changes

2023-03-09 20:16 UTC, merged