Further NXP P1021 fixes and improvements
wolfSSL/wolfBoot pull request #307
Opened 2023-05-12 16:58 UTC by dgarske

* Finalizing the full boot/update process.
* Currently first stage loader has issue with FCM/L1 changing when trying to relocate to DDR.

2023-06-22 12:50 UTC, danielinux commented on hal/nxp_p1021.c
> +    /* TODO - Ethernet*/
Remove "TODO" point or expand with a more verbose comment

2023-06-22 12:52 UTC, danielinux commented on hal/nxp_p1021.c
> +#if 0 /* ethernet (uec) setup not required */
Remove dead code or add another define to enable ethernet initialization from the config when appropriate

2023-06-22 12:53 UTC, danielinux commented on hal/nxp_p1021.c
> +#if 0 /* Disabled for wolfBoot */
Remove dead code or add a config define to enforce CRC checking when appropriate

2023-06-22 12:55 UTC, danielinux commented on hal/nxp_p1021.c
> +int qe_upload_firmware(const struct qe_firmware *firmware)
should this be static? It does not seem to be used outside of this module

2023-06-22 12:57 UTC, danielinux commented on hal/nxp_p1021.c
> +void hal_irq_init(void)
static?

2023-06-22 13:53 UTC, danielinux requested changes
minor comments, mostly on dead code and symbols visibility

2023-07-04 15:05 UTC, danielinux reviewed
Good to go. Please consider making hal_irq_init, hal_l2_init static

2023-07-04 16:26 UTC, dgarske commented
> Almost good to go. Please consider making hal_irq_init, hal_l2_init and other local functions static. Please expand the comment on the /* TODO */ regarding Ethernet mapping (i.e. why it's disabled). Please remove dead code (Ethernet initialization and CRC).

Hey Daniele,
I wanted to keep those non static so it would be possible to cal them individual

2023-07-04 17:02 UTC, dgarske commented
> 

Done. I kept the QE CRC code in case someone has crc32 function and wants to enable it later.

2023-07-04 20:13 UTC, danielinux requested changes
1- OK keeping the CRC code but please change if 0 into something more meaningful
2- Eth initialization: there is a "commented out" memcpy under `#if 0`, please use a meaningful define or eliminate dead code
3- some functions should still become static (see comments)
4- at the begining of nxp_p1021.c there is a vague comment "TODO - Ethernet" - please expand the todo with a sentence explaining what's missing, or remove the comment

2023-07-04 20:13 UTC, danielinux commented on hal/nxp_p1021.c
> +#if 0 /* Disabled for wolfBoot */
OK if you want to keep this, but please change `#if 0` into something meaninful like `#ifdef QE_CRC_VALIDATE` even if not present in the current config

2023-07-05 14:28 UTC, dgarske commented
> 1- OK keeping the CRC code but please change if 0 into something more meaningful
> 2- Eth initialization: there is a "commented out" memcpy under `#if 0`, please use a meaningful define or eliminate dead code
> 3- some functions should still become static (see comments)
> 4- at the begining of nxp_p1021.c there is a vague comment "TODO - Ethernet" - please expand the todo with a sentence explaining what's missing, or remove the comment

These issues are all fixed. Your comment says it was on "outdated". Please make sure you are reviewing the latest version.

2023-07-05 14:30 UTC, danielinux approved these changes

2023-07-05 15:03 UTC, merged