update sign to decode keys instead of assuming they're raw
wolfSSL/wolfBoot pull request #329
Opened 2023-07-26 22:38 UTC by jpbland1

add a github workflow for testing external partition signing
ZD 16491

2023-07-27 00:25 UTC, dgarske requested changes

2023-07-27 00:25 UTC, dgarske commented on tools/keytools/sign.c
> +#include "wolfboot/wolfboot.h"
Ideally we will want to update the sign.py version as well. If not we should document in Signing.md

2023-07-27 16:26 UTC, dgarske commented on tools/keytools/sign.c
> +#include "wolfboot/wolfboot.h"
@danielinux please let us know your thoughts on the topic.
If the wolfcrypt-py has the ECC public key decode (I believe it does) I think we should add it.

2023-07-27 19:01 UTC, dgarske approved these changes

2023-07-28 05:55 UTC, danielinux approved these changes

2023-07-28 05:55 UTC, merged