Simulator fixes and support for using MacOS
wolfSSL/wolfBoot pull request #334
Opened 2023-08-03 16:53 UTC by dgarske

* Added simulator support for Mac.
* Fix for simulator to properly assemble wolfboot.bin + signedtestapp + update + swap.
* Cleanup test-app linker flags.
* Fix simulator conflict with libwolfboot.o object.

2023-08-03 19:11 UTC, dgarske commented on include/hal.h
> +int hal_flash_write(uintptr_t address, const uint8_t *data, int len);
@danielinux , this change of mine seems like it could break some platforms. Perhaps I could just add a HAL build option to support 64-bit addresses?

2023-08-07 13:23 UTC, danielinux requested changes
Simulator test gives segmentation fault on linux.

Reproduce with:
`make test-sim-internal-flash-with-update`

then 
`tools/scripts/sim-sunnyday-update.sh`

I suspect two different strategies need to be used on Mac vs GNU due to the differences in mmap _"hint pointer"_ handling.

2023-08-07 15:18 UTC, dgarske commented
> Simulator test gives segmentation fault on linux.
> 
> Reproduce with: `make test-sim-internal-flash-with-update`
> 
> then `tools/scripts/sim-sunnyday-update.sh`
> 
> I suspect two different strategies need to be used on Mac vs GNU due to the differences in mmap _"hint pointer"_ handling.

@danielinux  I could not reproduce. What was your .config? I've only seen a set fault if mmap returns a 64-bit pointer and parts of the code assume 32-bit when the address gets passed around.

2023-08-07 18:52 UTC, danielinux commented
My bad, I was testing side-by-side, with the same config as `master`. I did not realize the address changed in the example config

2023-08-07 18:52 UTC, danielinux approved these changes

2023-08-07 18:54 UTC, merged