Support for Microchip Same51
wolfSSL/wolfBoot pull request #397
Opened 2023-12-22 12:05 UTC by danielinux

2024-01-31 23:11 UTC, dgarske requested changes

2024-01-31 23:11 UTC, dgarske commented on .gdbinit
> +add-symbol-file /home/dan/src/wolfboot/IDE/MPLabX/wolfBoot_usbUpdateApp.X/dist/default/production/wolfBoot_usbUpdateApp.X.production.elf
Consider reverting this.

2024-01-31 23:11 UTC, dgarske commented on IDE/MPLabX/wolfBoot-SAME51.X/Makefile
> +#
Please consider using `IDE/MPLABX` to match our other libraries and Microchip naming.

2024-01-31 23:11 UTC, dgarske commented on hal/same51.c
> +    uint32_t reg;
```hal/same51.c: In function 'hal_init':
hal/same51.c:280:14: error: unused variable 'reg' [-Werror=unused-variable]
  280 |     uint32_t reg;
      |              ^~~
```

2024-01-31 23:11 UTC, dgarske commented on hal/same51.c
> +static void RAMFUNCTION fork_bootloader(void)
Consider wrapping this in `DUALBANK_SWAP`.

```
hal/same51.c:263:25: error: 'fork_bootloader' defined but not used [-Werror=unused-function]
  263 | static void RAMFUNCTION fork_bootloader(void)
      |                         ^~~~~~~~~~~~~~~```

2024-01-31 23:11 UTC, dgarske commented on IDE/MPLabX/wolfBoot-SAME51.X/Makefile
> +#  There exist several targets which are by default empty and which can be
Please add a README.md for how to use these MPLABX projects.

2024-01-31 23:11 UTC, dgarske commented on hal/same51.c
> +static void RAMFUNCTION fork_bootloader(void)
I added `CFLAGS+=-Wunused -Wunused-parameter` to get these.

2024-02-15 10:21 UTC, danielinux commented
Thanks for the review, @dgarske . I should have addressed the comments + re-created the two MPLAB projects + provided extended documentation. This is now ready to consider for merging.

2024-02-15 17:05 UTC, merged