Fixes for NXP PT1024 with Integrity OS
wolfSSL/wolfBoot pull request #401
Opened 2024-01-26 01:12 UTC by dgarske

* Adds additional FDT fixups for FMAN, Ethernet, PCI. 
* Add PCI init and enumeration (incomplete - work in progress)

2024-02-03 21:22 UTC, dgarske commented
@danielinux this is a good state to merge. Fixes some bugs and adds features. I expect another to eventually to resolve a few outstanding issues.

2024-02-12 16:31 UTC, danielinux requested changes
Looks good. Some minor changes for readability

2024-02-12 16:31 UTC, danielinux commented on hal/nxp_t1024.c
> +    #ifdef DEBUG_PHY
Group under same ifdef?

2024-02-12 16:31 UTC, danielinux commented on src/pci.c
> +static inline void pci_dump_id(uint8_t bus, uint8_t dev, uint8_t fun)
this could be 
`#define pci_dump_id(...) do{}while(0)`  to save one symbol allocation

2024-02-12 16:31 UTC, danielinux commented on hal/nxp_t1024.c
> +        case 0x2000a231:
value is worth a define

2024-02-12 16:31 UTC, danielinux commented on hal/nxp_t1024.c
> +    if (reg == 0x95) {
Value is worth a define

2024-02-12 18:53 UTC, danielinux approved these changes

2024-02-12 18:54 UTC, merged