stm32l0: add support for external SPI flash
wolfSSL/wolfBoot pull request #41
Opened 2020-03-31 09:17 UTC by glennergeerts

2020-03-31 13:46 UTC, dgarske commented
Hi @glennergeerts , thank you for this submission adding STM32L0 external flash support. The changes look great.

In order to accept this we'll need a signed contributor agreement on file. Can you please email us directly at support@wolfssl.com and reference this PR? It would also be useful to hear about your project.

Thanks,
David Garske, wolfSSL

2020-11-05 10:35 UTC, danielinux requested changes
Please move pullup/output speed to hal_init(). The EWSR SPI command is indeed not necessary and can be removed.

2020-11-05 10:35 UTC, danielinux commented on hal/spi/spi_drv_stm32.c
> +
These changes don't work on STM32F4. I suggest to move these settings to the STM32L0 hal if they are needed for SPI to work on that platform.

2020-11-05 10:35 UTC, danielinux commented on src/spi_flash.c
> +    //spi_cmd(EWSR); // TODO not supported on every flash, but necessary for some models?
I have tested this change with SST25VF080B. The line is in fact not necessary and can be safely removed. Please remove the comment.

2020-11-20 11:23 UTC, merged

2020-11-20 11:24 UTC, danielinux commented
Merged! Thanks @glennergeerts