Support for STM32H5
wolfSSL/wolfBoot pull request #420
Opened 2024-03-15 13:29 UTC by danielinux

Initial import (untested)

2024-03-29 20:55 UTC, dgarske reviewed
Code looks good. It builds and I can flash it. The LED's on my board are not lighting up, so haven't been able to confirm boot is working yet.

2024-05-07 10:07 UTC, danielinux commented
@dgarske this is now working properly with Trustzone-M + secure wolfCrypt + PKCS11 app, and it is ready for review.

2024-05-07 21:06 UTC, dgarske requested changes

2024-05-07 21:06 UTC, dgarske commented on docs/Targets.md
> +Reboot the board to initiate an update via DUALBANK hw-assisted swap.
Still not getting any LED feedback. Having trouble getting the debugger setup. I tried with stm32h5.config and stm32h5-dualbank.config. My board is a NUCLEO-H563ZI and my TZEN=0xC3 (Trustzone disabled). Thoughts?

2024-05-09 14:42 UTC, dgarske approved these changes

2024-05-09 14:43 UTC, merged