Fix for error dereferencing type-punned pointer in update_flash.c `wolfBoot_swap_and_final_erase`
wolfSSL/wolfBoot pull request #473
Opened 2024-07-18 18:55 UTC by dgarske

Fix for update_flash.c `error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]`. Cleanup the swap logic for EXT_ENCRYPTED. Switch to using a uint32_t directly for checking tail magic.

```
src/update_flash.c: In function 'wolfBoot_swap_and_final_erase':
src/update_flash.c:237:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     if (*((uint32_t*)tmpBuffer) == WOLFBOOT_MAGIC_TRAIL) {
     ^
src/update_flash.c:261:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         *((uint32_t*)tmpBuffer) = WOLFBOOT_MAGIC_TRAIL;
         ^
cc1.exe: all warnings being treated as errors
```

2024-07-18 21:01 UTC, jpbland1 requested changes

2024-07-18 21:19 UTC, dgarske commented on src/update_flash.c
> +#   define TAIL_OFFSET_WORDS \
Tail is appropriate... "head" -> "tail". However it is "header" and "trailer", so fixed.

2024-07-18 21:21 UTC, jpbland1 commented on src/update_flash.c
> +#   define TAIL_OFFSET_WORDS \
gotcha, I was just thinking all our macro defines should use the same language for grep purposes

2024-07-18 21:21 UTC, jpbland1 submitted a review, later dismissed

2024-07-19 10:32 UTC, danielinux approved these changes

2024-07-19 10:44 UTC, danielinux approved these changes

2024-07-19 10:52 UTC, merged