Support for Microchip SAMA5D3
wolfSSL/wolfBoot pull request #494
Opened 2024-08-23 05:10 UTC by danielinux

Add support for ATSAMA5D3. 
This is wolfBoot's first 32-bit Cortex-A target, using `boot_arm32.c` and a reset vector in assembly `boot_arm32_start.S`.

2024-10-01 19:01 UTC, dgarske requested changes
Very nice! Just a few minor comments.

2024-10-01 19:01 UTC, dgarske commented on hal/sama5d3.c
> +void zynq_init(uint32_t cpu_clock)
Fairly sure you can remove this.

2024-10-01 19:01 UTC, dgarske commented on hal/sama5d3.c
> +{
Might consider TODO comment and `(void)cpu_clock`, etc.

2024-10-02 08:23 UTC, danielinux commented on hal/sama5d3.c
> +static uint32_t div(uint32_t dividend, uint32_t divisor)
I don't think it'd be generic enough. Let's consider moving to ARM32 port file later, if this comes up again on another 32bit ARM

2024-10-02 15:13 UTC, dgarske approved these changes
Very nice!

2024-10-02 15:13 UTC, merged