Fix flash interactions for i.MX RT targets
wolfSSL/wolfBoot pull request #495
Opened 2024-08-23 06:41 UTC by MulattoKid

This PR does a few things:
1. Enable `RAM_CODE=1` in all i.MX RT target example configs. When running XIP this is needed to ensure `memcpy` (which is used during `hal_flash_write`) is in RAM, and not flash as that could result in reading from flash while writing to flash.
2. Change both `CPU_MIMXRT1061CVJ5B` and `CPU_MIMXRT1042XJM5B` to define the `USE_GET_CONFIG` macro. This makes the flash configuration's LUT a lot smaller, and the MCU will instead query the various settings from the flash chip. Note that the `CPU_MIMXRT1052DVJ6B` target (RT1050 family) doesn't support this option.
3. Ensure the arguments passed to `DCACHE_InvalidateByRange` both are 32-byte aligned (required by the function as cache lines are 32 bytes)
4. Move the call to `DCACHE_InvalidateByRange` to be outside the for-loop in `hal_flash_write`. This is needed to ensure reads aren't performed to flash (i.e. to read the code for the function) while writes are happening, as that's not allowed behavior. Another option would be to move the function from flash to RAM, but that is a bit more involved so I opted for this solution.
5. Change the return pattern for `hal_flash_write` to only have one return statement (to avoid duplicate code due to below point)
6. Add a data synchronization barrier (`asm volatile ("dsb")`) after accessing flash through the FlexSPI ROM API to ensure speculative pre-fetching doesn't violate the rule about reading from flash while erasing/programming it

I've tested this several times now, and am not able to hit the hang issue we've seen before (see issue ref below).

Ref:
- Based on PRs:
  - https://github.com/wolfSSL/wolfBoot/pull/492
  - https://github.com/wolfSSL/wolfBoot/pull/493
- Issue: https://github.com/wolfSSL/wolfBoot/issues/489

2024-08-23 19:20 UTC, bigbrett requested changes
Looks great, just one quick fix needed on return values. I can fix other nits in a subsequent PR, as I have some fixes for 1064 to add.

Let me know if your testing has turned up any further hanging, or if it still running smoothly with these changes.

2024-08-23 19:20 UTC, bigbrett commented on hal/imx_rt.c
> +    return program_success;
Although our return checking for writes is lax, technically this function should return 0 on sucess and -1 on failure, according to the docs. If we could strip the use of `bool` and return these codes that would be great

2024-08-26 06:21 UTC, MulattoKid commented
> Let me know if your testing has turned up any further hanging, or if it still running smoothly with these changes.

Have tested some more, and still no issues :+1:

2024-08-26 14:58 UTC, bigbrett approved these changes

2024-08-26 14:59 UTC, merged